let LEVELS = [
  {difficulty:"easy",name:"First Flow",par:8,time:28,hint:"Learn the flow. Easy should still feel like a puzzle.",blocks:[{id:"r1",color:"red",x:1,y:4},{id:"b1",color:"blue",x:4,y:1},{id:"g1",color:"green",x:2,y:2}],gates:[{color:"red",side:"left",pos:4},{color:"blue",side:"top",pos:4},{color:"green",side:"bottom",pos:2}],walls:[]},
  {difficulty:"easy",name:"Crossing Paths",par:8,time:34,hint:"The shortest-looking route is not always the cleanest.",blocks:[{id:"r1",color:"red",x:4,y:3},{id:"b1",color:"blue",x:1,y:3},{id:"y1",color:"yellow",x:3,y:1}],gates:[{color:"red",side:"right",pos:3},{color:"blue",side:"left",pos:3},{color:"yellow",side:"top",pos:3}],walls:[{x:2,y:2},{x:3,y:2}]},
  {difficulty:"easy",name:"Make Space",par:12,time:38,hint:"Your first move may need to create space, not score progress.",blocks:[{id:"r1",color:"red",x:2,y:4},{id:"b1",color:"blue",x:3,y:4},{id:"g1",color:"green",x:2,y:1},{id:"y1",color:"yellow",x:3,y:1}],gates:[{color:"red",side:"left",pos:4},{color:"blue",side:"right",pos:4},{color:"green",side:"left",pos:1},{color:"yellow",side:"right",pos:1}],walls:[{x:0,y:2},{x:5,y:2}]},
  {difficulty:"intermediate",name:"The Funnel",par:10,time:44,hint:"Four blocks share two narrow lanes. Pick the order.",blocks:[{id:"r1",color:"red",x:2,y:4},{id:"b1",color:"blue",x:3,y:4},{id:"g1",color:"green",x:2,y:0},{id:"p1",color:"purple",x:3,y:0}],gates:[{color:"red",side:"bottom",pos:2},{color:"blue",side:"bottom",pos:3},{color:"green",side:"top",pos:2},{color:"purple",side:"top",pos:3}],walls:[{x:1,y:2},{x:4,y:2},{x:1,y:3},{x:4,y:3}]},
  {difficulty:"intermediate",name:"Traffic",par:14,time:48,hint:"Every block wants a different direction. Untangle the center first.",blocks:[{id:"r1",color:"red",x:2,y:2},{id:"b1",color:"blue",x:3,y:2},{id:"g1",color:"green",x:2,y:3},{id:"y1",color:"yellow",x:3,y:3}],gates:[{color:"red",side:"top",pos:2},{color:"blue",side:"right",pos:2},{color:"green",side:"left",pos:3},{color:"yellow",side:"bottom",pos:3}],walls:[{x:0,y:0},{x:5,y:5}]},
  {difficulty:"intermediate",name:"Split Decision",par:12,time:52,hint:"Same colors, opposite exits. Do not send the wrong twin across the board.",blocks:[{id:"r1",color:"red",x:1,y:1},{id:"r2",color:"red",x:4,y:4},{id:"b1",color:"blue",x:4,y:1},{id:"b2",color:"blue",x:1,y:4}],gates:[{color:"red",side:"left",pos:1},{color:"red",side:"right",pos:4},{color:"blue",side:"right",pos:1},{color:"blue",side:"left",pos:4}],walls:[{x:2,y:2},{x:3,y:3}]},
  {difficulty:"hard",name:"Tight Corners",par:16,time:58,hint:"The wall divides the board. Route around it before committing.",blocks:[{id:"r1",color:"red",x:2,y:1},{id:"b1",color:"blue",x:3,y:1},{id:"g1",color:"green",x:2,y:4},{id:"p1",color:"purple",x:3,y:4}],gates:[{color:"red",side:"left",pos:1},{color:"blue",side:"right",pos:1},{color:"green",side:"left",pos:4},{color:"purple",side:"right",pos:4}],walls:[{x:1,y:2},{x:2,y:2},{x:3,y:2},{x:4,y:2}]},
  {difficulty:"hard",name:"Center Jam",par:18,time:62,hint:"Five blocks compete for the same breathing room. Plan several moves ahead.",blocks:[{id:"r1",color:"red",x:2,y:2},{id:"b1",color:"blue",x:3,y:2},{id:"g1",color:"green",x:2,y:3},{id:"y1",color:"yellow",x:3,y:3},{id:"p1",color:"purple",x:1,y:3}],gates:[{color:"red",side:"top",pos:2},{color:"blue",side:"top",pos:3},{color:"green",side:"bottom",pos:2},{color:"yellow",side:"bottom",pos:3},{color:"purple",side:"left",pos:3}],walls:[{x:0,y:1},{x:5,y:1},{x:0,y:4},{x:5,y:4}]},
  {difficulty:"hard",name:"Five Ways",par:18,time:66,hint:"Five exits, five directions, very little room for wasted motion.",blocks:[{id:"r1",color:"red",x:2,y:1},{id:"b1",color:"blue",x:3,y:1},{id:"g1",color:"green",x:1,y:3},{id:"y1",color:"yellow",x:4,y:3},{id:"p1",color:"purple",x:2,y:4}],gates:[{color:"red",side:"top",pos:2},{color:"blue",side:"top",pos:3},{color:"green",side:"left",pos:3},{color:"yellow",side:"right",pos:3},{color:"purple",side:"bottom",pos:2}],walls:[{x:2,y:2},{x:3,y:2}]},
  {difficulty:"extreme",name:"Pressure Test",par:20,time:72,hint:"Extreme starts here. Expect setup moves and misleading open lanes.",blocks:[{id:"r1",color:"red",x:1,y:1},{id:"b1",color:"blue",x:4,y:1},{id:"g1",color:"green",x:1,y:4},{id:"y1",color:"yellow",x:4,y:4},{id:"p1",color:"purple",x:2,y:3}],gates:[{color:"red",side:"left",pos:1},{color:"blue",side:"right",pos:1},{color:"green",side:"left",pos:4},{color:"yellow",side:"right",pos:4},{color:"purple",side:"bottom",pos:2}],walls:[{x:2,y:2},{x:3,y:2},{x:3,y:3}]},
  {difficulty:"extreme",name:"Long Route",par:22,time:78,hint:"The obvious direction is bait. Build the route before chasing an exit.",blocks:[{id:"r1",color:"red",x:4,y:0},{id:"b1",color:"blue",x:1,y:0},{id:"g1",color:"green",x:4,y:5},{id:"y1",color:"yellow",x:1,y:5},{id:"p1",color:"purple",x:2,y:2}],gates:[{color:"red",side:"right",pos:0},{color:"blue",side:"left",pos:0},{color:"green",side:"right",pos:5},{color:"yellow",side:"left",pos:5},{color:"purple",side:"top",pos:2}],walls:[{x:2,y:1},{x:3,y:1},{x:2,y:4},{x:3,y:4}]},
  {difficulty:"extreme",name:"Flow State",par:24,time:88,hint:"No tutorial move. Read the whole board, then commit.",blocks:[{id:"r1",color:"red",x:1,y:2},{id:"r2",color:"red",x:4,y:3},{id:"b1",color:"blue",x:4,y:2},{id:"b2",color:"blue",x:1,y:3},{id:"g1",color:"green",x:2,y:1},{id:"p1",color:"purple",x:3,y:4}],gates:[{color:"red",side:"left",pos:2},{color:"red",side:"right",pos:3},{color:"blue",side:"right",pos:2},{color:"blue",side:"left",pos:3},{color:"green",side:"top",pos:2},{color:"purple",side:"bottom",pos:3}],walls:[{x:2,y:2},{x:3,y:3}]}
];
const DIFFICULTIES=["easy","intermediate","hard","extreme"];
const DIFFICULTY_LABELS={easy:"Easy",intermediate:"Intermediate",hard:"Hard",extreme:"Extreme ☠️"};
const ACTIVE_DIFFICULTY=DIFFICULTIES.includes(localStorage.getItem("bf-difficulty"))?localStorage.getItem("bf-difficulty"):"easy";
LEVELS=LEVELS.filter(level=>level.difficulty===ACTIVE_DIFFICULTY);
