const ALL_LEVELS = [
  // EASY — approachable, but each level asks for a different idea.
  {difficulty:"easy",name:"First Flow",cols:5,rows:5,par:7,time:32,mechanics:["Slide","Match"],hint:"Clear all three colors. Think about lanes before swiping.",blocks:[{id:"r1",color:"red",x:1,y:3},{id:"b1",color:"blue",x:3,y:1},{id:"g1",color:"green",x:2,y:2}],gates:[{color:"red",x:0,y:3,dir:"left"},{color:"blue",x:3,y:0,dir:"up"},{color:"green",x:2,y:4,dir:"down"}]},
  {difficulty:"easy",name:"Corner Cut",cols:5,rows:5,par:8,time:35,mechanics:["Irregular board"],hint:"Missing tiles change what counts as an edge.",voids:[{x:3,y:0},{x:4,y:0},{x:4,y:1}],walls:[{x:2,y:2}],blocks:[{id:"r1",color:"red",x:1,y:3},{id:"b1",color:"blue",x:2,y:1},{id:"y1",color:"yellow",x:3,y:3}],gates:[{color:"red",x:0,y:3,dir:"left"},{color:"blue",x:2,y:0,dir:"up"},{color:"yellow",x:4,y:3,dir:"right"}]},
  {difficulty:"easy",name:"The Lane",cols:7,rows:5,par:10,time:38,mechanics:["Corridors"],hint:"Use the openings instead of fighting the walls.",walls:[{x:3,y:0},{x:3,y:1},{x:3,y:3},{x:3,y:4}],blocks:[{id:"r1",color:"red",x:1,y:1},{id:"b1",color:"blue",x:5,y:3},{id:"g1",color:"green",x:2,y:2}],gates:[{color:"red",x:0,y:1,dir:"left"},{color:"blue",x:6,y:3,dir:"right"},{color:"green",x:6,y:2,dir:"right"}]},
  {difficulty:"easy",name:"Long Haul",cols:6,rows:6,par:8,time:42,mechanics:["Long blocks"],hint:"Long blocks take more room, so keep their lane clear.",blocks:[{id:"r1",color:"red",x:1,y:4,w:2,h:1},{id:"b1",color:"blue",x:4,y:1,w:1,h:2},{id:"g1",color:"green",x:2,y:2}],gates:[{color:"red",x:0,y:4,dir:"left"},{color:"blue",x:4,y:0,dir:"up"},{color:"green",x:2,y:5,dir:"down"}]},
  {difficulty:"easy",name:"Ice Break",cols:6,rows:5,par:7,time:42,mechanics:["Ice ❄"],hint:"Once a block hits ice, it keeps sliding in that direction.",ice:[{x:2,y:2},{x:3,y:2},{x:4,y:2}],blocks:[{id:"b1",color:"blue",x:1,y:2},{id:"r1",color:"red",x:1,y:4},{id:"g1",color:"green",x:4,y:0}],gates:[{color:"blue",x:5,y:2,dir:"right"},{color:"red",x:0,y:4,dir:"left"},{color:"green",x:4,y:0,dir:"up"}]},
  {difficulty:"easy",name:"Warp 101",cols:6,rows:6,par:8,time:46,mechanics:["Portals ◎"],hint:"Step onto a portal to jump to its partner.",portals:[{id:"A",a:{x:2,y:4},b:{x:4,y:1}}],blocks:[{id:"g1",color:"green",x:1,y:4},{id:"r1",color:"red",x:1,y:1},{id:"y1",color:"yellow",x:3,y:5}],gates:[{color:"green",x:5,y:1,dir:"right"},{color:"red",x:0,y:1,dir:"left"},{color:"yellow",x:3,y:5,dir:"down"}]},

  // INTERMEDIATE — dependencies and rule changes.
  {difficulty:"intermediate",name:"Open the Door",cols:6,rows:6,par:10,time:50,mechanics:["Switch ◆","Barrier ▥"],hint:"Touch the switch first. The matching barrier stays open after activation.",switches:[{id:"A",x:1,y:4}],barriers:[{id:"A",x:3,y:2}],blocks:[{id:"b1",color:"blue",x:1,y:3},{id:"r1",color:"red",x:2,y:2},{id:"g1",color:"green",x:4,y:4}],gates:[{color:"blue",x:1,y:5,dir:"down"},{color:"red",x:5,y:2,dir:"right"},{color:"green",x:5,y:4,dir:"right"}]},
  {difficulty:"intermediate",name:"Arrow Room",cols:6,rows:6,par:11,time:52,mechanics:["One-way →"],hint:"An arrow controls the direction of the block sitting on it.",oneWays:[{x:2,y:3,dir:"up"},{x:4,y:2,dir:"right"}],walls:[{x:3,y:3}],blocks:[{id:"r1",color:"red",x:2,y:3},{id:"b1",color:"blue",x:4,y:2},{id:"y1",color:"yellow",x:1,y:4}],gates:[{color:"red",x:2,y:0,dir:"up"},{color:"blue",x:5,y:2,dir:"right"},{color:"yellow",x:0,y:4,dir:"left"}]},
  {difficulty:"intermediate",name:"Blue First",cols:6,rows:6,par:9,time:54,mechanics:["Exit order"],hint:"The exits work, but only in the displayed order.",exitOrder:["blue","red","green"],blocks:[{id:"r1",color:"red",x:1,y:2},{id:"b1",color:"blue",x:4,y:1},{id:"g1",color:"green",x:3,y:4}],gates:[{color:"red",x:0,y:2,dir:"left"},{color:"blue",x:4,y:0,dir:"up"},{color:"green",x:3,y:5,dir:"down"}]},
  {difficulty:"intermediate",name:"Broken Square",cols:7,rows:6,par:13,time:58,mechanics:["Irregular board","Internal exits"],hint:"Some exits are on the edge of a hole, not the outside wall.",voids:[{x:3,y:0},{x:3,y:1},{x:3,y:4},{x:3,y:5},{x:0,y:0},{x:6,y:5}],walls:[{x:2,y:3},{x:4,y:2}],blocks:[{id:"r1",color:"red",x:1,y:1},{id:"b1",color:"blue",x:5,y:4},{id:"p1",color:"purple",x:2,y:4}],gates:[{color:"red",x:2,y:1,dir:"right"},{color:"blue",x:4,y:4,dir:"left"},{color:"purple",x:2,y:5,dir:"down"}]},
  {difficulty:"intermediate",name:"Blocked Warp",cols:7,rows:6,par:14,time:60,mechanics:["Portals ◎","Traffic"],hint:"A portal only fires when its destination has room.",portals:[{id:"A",a:{x:2,y:4},b:{x:5,y:1}}],blocks:[{id:"r1",color:"red",x:1,y:4},{id:"b1",color:"blue",x:5,y:1},{id:"g1",color:"green",x:4,y:3}],gates:[{color:"red",x:6,y:1,dir:"right"},{color:"blue",x:5,y:0,dir:"up"},{color:"green",x:4,y:5,dir:"down"}]},
  {difficulty:"intermediate",name:"Ice Traffic",cols:7,rows:6,par:13,time:62,mechanics:["Ice ❄","Order"],hint:"Clear the landing zone before sending a block down the ice lane.",ice:[{x:2,y:2},{x:3,y:2},{x:4,y:2},{x:4,y:3},{x:4,y:4}],walls:[{x:3,y:3}],blocks:[{id:"b1",color:"blue",x:1,y:2},{id:"r1",color:"red",x:5,y:2},{id:"g1",color:"green",x:4,y:5}],gates:[{color:"blue",x:6,y:2,dir:"right"},{color:"red",x:6,y:2,dir:"right"},{color:"green",x:4,y:5,dir:"down"}]},

  // HARD — mechanics start stacking.
  {difficulty:"hard",name:"Double Lock",cols:7,rows:7,par:18,time:70,mechanics:["2 switches","2 barriers"],hint:"Each switch opens only its matching barrier. Choose which lane to unlock first.",switches:[{id:"A",x:1,y:5},{id:"B",x:5,y:1}],barriers:[{id:"A",x:3,y:4},{id:"B",x:3,y:2}],walls:[{x:3,y:0},{x:3,y:1},{x:3,y:3},{x:3,y:5},{x:3,y:6}],blocks:[{id:"r1",color:"red",x:2,y:4},{id:"b1",color:"blue",x:4,y:2},{id:"g1",color:"green",x:1,y:4},{id:"y1",color:"yellow",x:5,y:2}],gates:[{color:"red",x:6,y:4,dir:"right"},{color:"blue",x:0,y:2,dir:"left"},{color:"green",x:1,y:6,dir:"down"},{color:"yellow",x:5,y:0,dir:"up"}]},
  {difficulty:"hard",name:"Crosswind",cols:7,rows:7,par:18,time:72,mechanics:["One-way →","Irregular board"],hint:"The shape gives you room, the arrows take some of it back.",voids:[{x:0,y:0},{x:1,y:0},{x:5,y:0},{x:6,y:0},{x:0,y:6},{x:1,y:6},{x:5,y:6},{x:6,y:6}],oneWays:[{x:3,y:4,dir:"up"},{x:2,y:3,dir:"left"},{x:4,y:3,dir:"right"}],blocks:[{id:"r1",color:"red",x:3,y:4},{id:"b1",color:"blue",x:2,y:3},{id:"g1",color:"green",x:4,y:3},{id:"p1",color:"purple",x:3,y:2}],gates:[{color:"red",x:3,y:0,dir:"up"},{color:"blue",x:0,y:3,dir:"left"},{color:"green",x:6,y:3,dir:"right"},{color:"purple",x:3,y:6,dir:"down"}]},
  {difficulty:"hard",name:"Portal Traffic",cols:7,rows:7,par:20,time:76,mechanics:["2 portals","Traffic"],hint:"The fastest route may be unavailable until another block clears a destination.",portals:[{id:"A",a:{x:1,y:5},b:{x:5,y:1}},{id:"B",a:{x:1,y:1},b:{x:5,y:5}}],walls:[{x:3,y:2},{x:3,y:3},{x:3,y:4}],blocks:[{id:"r1",color:"red",x:1,y:4},{id:"b1",color:"blue",x:5,y:1},{id:"g1",color:"green",x:1,y:2},{id:"y1",color:"yellow",x:5,y:5}],gates:[{color:"red",x:6,y:1,dir:"right"},{color:"blue",x:5,y:0,dir:"up"},{color:"green",x:6,y:5,dir:"right"},{color:"yellow",x:5,y:6,dir:"down"}]},
  {difficulty:"hard",name:"Cold Storage",cols:7,rows:7,par:19,time:78,mechanics:["Ice ❄","Switch ◆","Barrier ▥"],hint:"Ice can carry you onto a switch — or past the space you needed.",ice:[{x:1,y:3},{x:2,y:3},{x:3,y:3},{x:4,y:3}],switches:[{id:"A",x:4,y:3}],barriers:[{id:"A",x:5,y:1}],walls:[{x:2,y:1},{x:3,y:1}],blocks:[{id:"b1",color:"blue",x:0,y:3},{id:"r1",color:"red",x:4,y:1},{id:"g1",color:"green",x:2,y:5}],gates:[{color:"blue",x:6,y:3,dir:"right"},{color:"red",x:6,y:1,dir:"right"},{color:"green",x:2,y:6,dir:"down"}]},
  {difficulty:"hard",name:"Big Pieces",cols:7,rows:7,par:17,time:80,mechanics:["Long blocks","Corridors"],hint:"Long blocks can become moving walls. Park them carefully.",walls:[{x:3,y:1},{x:3,y:5}],blocks:[{id:"r1",color:"red",x:1,y:2,w:2,h:1},{id:"b1",color:"blue",x:4,y:4,w:2,h:1},{id:"g1",color:"green",x:2,y:4},{id:"p1",color:"purple",x:4,y:2}],gates:[{color:"red",x:0,y:2,dir:"left"},{color:"blue",x:6,y:4,dir:"right"},{color:"green",x:2,y:6,dir:"down"},{color:"purple",x:4,y:0,dir:"up"}]},
  {difficulty:"hard",name:"Sequence Breaker",cols:7,rows:7,par:22,time:84,mechanics:["Exit order","Switch ◆","Barrier ▥"],hint:"The required exit order and the locked lane pull you in opposite directions.",exitOrder:["green","blue","red","yellow"],switches:[{id:"A",x:2,y:5}],barriers:[{id:"A",x:4,y:1}],blocks:[{id:"r1",color:"red",x:4,y:2},{id:"b1",color:"blue",x:1,y:1},{id:"g1",color:"green",x:2,y:4},{id:"y1",color:"yellow",x:5,y:4}],gates:[{color:"green",x:2,y:6,dir:"down"},{color:"blue",x:0,y:1,dir:"left"},{color:"red",x:4,y:0,dir:"up"},{color:"yellow",x:6,y:4,dir:"right"}]},

  // EXTREME — combinations, deceptive routes and more setup moves.
  {difficulty:"extreme",name:"False Start",cols:7,rows:7,par:24,time:92,mechanics:["Exit order","Portals ◎"],hint:"Several exits look ready. Only one sequence keeps the board open.",exitOrder:["blue","purple","red","green"],portals:[{id:"A",a:{x:1,y:5},b:{x:5,y:1}}],walls:[{x:3,y:2},{x:3,y:3},{x:3,y:4}],blocks:[{id:"r1",color:"red",x:1,y:2},{id:"b1",color:"blue",x:5,y:2},{id:"g1",color:"green",x:1,y:4},{id:"p1",color:"purple",x:2,y:5}],gates:[{color:"blue",x:6,y:2,dir:"right"},{color:"purple",x:6,y:1,dir:"right"},{color:"red",x:0,y:2,dir:"left"},{color:"green",x:0,y:4,dir:"left"}]},
  {difficulty:"extreme",name:"Thin Ice",cols:8,rows:7,par:26,time:96,mechanics:["Ice ❄","One-way →"],hint:"Momentum and arrows remove your ability to correct a bad setup move.",ice:[{x:2,y:3},{x:3,y:3},{x:4,y:3},{x:5,y:3},{x:5,y:4}],oneWays:[{x:1,y:3,dir:"right"},{x:5,y:5,dir:"up"}],walls:[{x:3,y:2},{x:4,y:4}],blocks:[{id:"r1",color:"red",x:1,y:3},{id:"b1",color:"blue",x:5,y:5},{id:"g1",color:"green",x:6,y:1},{id:"y1",color:"yellow",x:1,y:5}],gates:[{color:"red",x:7,y:3,dir:"right"},{color:"blue",x:5,y:0,dir:"up"},{color:"green",x:7,y:1,dir:"right"},{color:"yellow",x:0,y:5,dir:"left"}]},
  {difficulty:"extreme",name:"Two Keys",cols:8,rows:7,par:28,time:100,mechanics:["2 switches","Portals ◎","Barriers ▥"],hint:"The keys are on opposite sides. The portal is the bridge — if its landing cell stays free.",switches:[{id:"A",x:1,y:5},{id:"B",x:6,y:1}],barriers:[{id:"A",x:5,y:4},{id:"B",x:2,y:2}],portals:[{id:"A",a:{x:2,y:5},b:{x:5,y:1}}],walls:[{x:3,y:3},{x:4,y:3}],blocks:[{id:"r1",color:"red",x:1,y:4},{id:"b1",color:"blue",x:6,y:2},{id:"g1",color:"green",x:2,y:4},{id:"p1",color:"purple",x:5,y:2}],gates:[{color:"red",x:7,y:4,dir:"right"},{color:"blue",x:0,y:2,dir:"left"},{color:"green",x:2,y:6,dir:"down"},{color:"purple",x:5,y:0,dir:"up"}]},
  {difficulty:"extreme",name:"Split Chamber",cols:8,rows:7,par:28,time:104,mechanics:["Irregular board","Portals ◎","Internal exits"],hint:"The board is split into chambers. Treat portals like hallways and holes like edges.",voids:[{x:3,y:0},{x:4,y:0},{x:3,y:1},{x:4,y:1},{x:3,y:2},{x:4,y:2},{x:3,y:4},{x:4,y:4},{x:3,y:5},{x:4,y:5},{x:3,y:6},{x:4,y:6}],portals:[{id:"A",a:{x:2,y:3},b:{x:5,y:3}}],blocks:[{id:"r1",color:"red",x:1,y:1},{id:"b1",color:"blue",x:6,y:5},{id:"g1",color:"green",x:1,y:5},{id:"y1",color:"yellow",x:6,y:1}],gates:[{color:"red",x:2,y:1,dir:"right"},{color:"blue",x:5,y:5,dir:"left"},{color:"green",x:0,y:5,dir:"left"},{color:"yellow",x:7,y:1,dir:"right"}]},
  {difficulty:"extreme",name:"Moving Walls",cols:8,rows:8,par:30,time:108,mechanics:["Long blocks","Switch ◆","One-way →"],hint:"The long blocks are both cargo and obstacles. Moving one changes the whole maze.",switches:[{id:"A",x:2,y:6}],barriers:[{id:"A",x:6,y:3}],oneWays:[{x:4,y:5,dir:"up"}],walls:[{x:3,y:3},{x:4,y:3}],blocks:[{id:"r1",color:"red",x:1,y:2,w:2,h:1},{id:"b1",color:"blue",x:5,y:5,w:2,h:1},{id:"g1",color:"green",x:2,y:5},{id:"p1",color:"purple",x:4,y:5},{id:"y1",color:"yellow",x:6,y:2}],gates:[{color:"red",x:0,y:2,dir:"left"},{color:"blue",x:7,y:5,dir:"right"},{color:"green",x:2,y:7,dir:"down"},{color:"purple",x:4,y:0,dir:"up"},{color:"yellow",x:7,y:2,dir:"right"}]},
  {difficulty:"extreme",name:"The Gauntlet",cols:8,rows:8,par:34,time:118,mechanics:["Ice ❄","Portal ◎","Switch ◆","Exit order"],hint:"Read the entire board first. Every mechanic matters and every early move changes a later lane.",exitOrder:["green","blue","purple","red","yellow"],ice:[{x:1,y:4},{x:2,y:4},{x:3,y:4}],portals:[{id:"A",a:{x:3,y:6},b:{x:6,y:1}}],switches:[{id:"A",x:3,y:4}],barriers:[{id:"A",x:5,y:2}],oneWays:[{x:6,y:5,dir:"up"}],walls:[{x:4,y:2},{x:4,y:3},{x:4,y:5}],blocks:[{id:"r1",color:"red",x:1,y:2},{id:"b1",color:"blue",x:6,y:2},{id:"g1",color:"green",x:0,y:4},{id:"p1",color:"purple",x:3,y:6},{id:"y1",color:"yellow",x:6,y:5}],gates:[{color:"green",x:7,y:4,dir:"right"},{color:"blue",x:7,y:2,dir:"right"},{color:"purple",x:7,y:1,dir:"right"},{color:"red",x:0,y:2,dir:"left"},{color:"yellow",x:6,y:0,dir:"up"}]}
];

const DIFFICULTIES=["easy","intermediate","hard","extreme"];
const DIFFICULTY_LABELS={easy:"Easy",intermediate:"Intermediate",hard:"Hard",extreme:"Extreme ☠️"};
const savedDifficulty=localStorage.getItem("bf-difficulty");
const ACTIVE_DIFFICULTY=DIFFICULTIES.includes(savedDifficulty)?savedDifficulty:"easy";
let LEVELS=ALL_LEVELS.filter(item=>item.difficulty===ACTIVE_DIFFICULTY);
